FROM node:18-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm cache clean --force && npm config set registry https://registry.npmjs.org/
RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.21-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]